[package]
name = "open_with"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.9.6"

[target.'cfg(target_os = "macos")'.dependencies]
osascript = "0.3.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3.9"